# Loop 24 Strategic Analysis

## Current Status
- Best CV/LB: 70.626088
- Target: 68.919154
- Gap: 1.707 (2.47%)
- Submissions used: 10/100 (90 remaining)

## Key Insight from Analysis
The gap is 1.707 points. To close this:
- 10% improvement on worst 50 N values would close 111.7% of gap
- 15% improvement on N=1-20 would close 70.8% of gap

## What's Been Tried (25 experiments)
1. bbox3 optimization - produces overlaps
2. SA optimization - converges to same local optimum
3. Tessellation - no improvement
4. Random restart SA - worse than baseline
5. Genetic algorithm - no improvement
6. Grid-based solutions - 25% worse
7. Ensemble from sources - 0.017 improvement
8. Asymmetric configurations - all worse
9. Exhaustive search N=1,2 - baseline optimal
10. Constraint programming - no improvement
11. Gradient descent - zero gradient
12. Deletion cascade - 0.0015 improvement (N=87)

In [1]:
# Load and analyze current best submission
import pandas as pd
import numpy as np
from shapely.geometry import Polygon
from shapely.affinity import rotate, translate

TREE_TEMPLATE = [
    (0.0, 0.8), (0.125, 0.5), (0.0625, 0.5), (0.2, 0.25), (0.1, 0.25),
    (0.35, 0.0), (0.075, 0.0), (0.075, -0.2), (-0.075, -0.2), (-0.075, 0.0),
    (-0.35, 0.0), (-0.1, 0.25), (-0.2, 0.25), (-0.0625, 0.5), (-0.125, 0.5)
]

def parse_s_value(val):
    if isinstance(val, str) and val.startswith('s'):
        return float(val[1:])
    return float(val)

def create_tree_polygon(x, y, angle):
    tree = Polygon(TREE_TEMPLATE)
    tree = rotate(tree, angle, origin=(0, 0), use_radians=False)
    tree = translate(tree, x, y)
    return tree

def get_bounding_box_side(trees):
    all_x, all_y = [], []
    for tree in trees:
        minx, miny, maxx, maxy = tree.bounds
        all_x.extend([minx, maxx])
        all_y.extend([miny, maxy])
    return max(max(all_x) - min(all_x), max(all_y) - min(all_y))

df = pd.read_csv('/home/submission/submission.csv')
df['x'] = df['x'].apply(parse_s_value)
df['y'] = df['y'].apply(parse_s_value)
df['deg'] = df['deg'].apply(parse_s_value)
df['n'] = df['id'].apply(lambda x: int(x.split('_')[0]))

# Calculate scores
scores = {}
for n in range(1, 201):
    group = df[df['n'] == n]
    trees = [create_tree_polygon(row['x'], row['y'], row['deg']) for _, row in group.iterrows()]
    side = get_bounding_box_side(trees)
    scores[n] = (side ** 2) / n

print(f"Current total: {sum(scores.values()):.6f}")
print(f"Target: 68.919154")
print(f"Gap: {sum(scores.values()) - 68.919154:.6f}")

Current total: 70.624424
Target: 68.919154
Gap: 1.705270


In [2]:
# Analyze score distribution by N range
ranges = [
    (1, 10, 'N=1-10'),
    (11, 20, 'N=11-20'),
    (21, 50, 'N=21-50'),
    (51, 100, 'N=51-100'),
    (101, 150, 'N=101-150'),
    (151, 200, 'N=151-200')
]

print("Score contribution by range:")
for start, end, label in ranges:
    range_total = sum(scores[n] for n in range(start, end+1))
    pct = range_total / sum(scores.values()) * 100
    print(f"  {label}: {range_total:.4f} ({pct:.1f}%)")

# Calculate efficiency by range
tree_area = Polygon(TREE_TEMPLATE).area
print(f"\nEfficiency by range (higher = better packing):")
for start, end, label in ranges:
    range_scores = [scores[n] for n in range(start, end+1)]
    avg_efficiency = sum(tree_area / s for s in range_scores) / len(range_scores)
    print(f"  {label}: {avg_efficiency:.4f}")

Score contribution by range:
  N=1-10: 4.3291 (6.1%)
  N=11-20: 3.7240 (5.3%)
  N=21-50: 10.9801 (15.5%)
  N=51-100: 17.6119 (24.9%)
  N=101-150: 17.1363 (24.3%)
  N=151-200: 16.8430 (23.8%)

Efficiency by range (higher = better packing):
  N=1-10: 0.5813
  N=11-20: 0.6596
  N=21-50: 0.6712
  N=51-100: 0.6975
  N=101-150: 0.7168
  N=151-200: 0.7292


## Key Observations

1. **Small N (1-10) has worst efficiency** - These contribute 11.4% of score but have only 37-65% efficiency
2. **Large N (150-200) has best efficiency** - These contribute 23.5% of score with 73-75% efficiency
3. **The gap is 2.47%** - This is significant but achievable

## What the Research Says

From web research and discussions:
1. Top teams use **high-precision arithmetic (Decimal type)** - we're using float
2. Top teams use **asymmetric layouts** - but our tests showed symmetric is better
3. Top teams use **exact geometric algorithms** - not SA/heuristics
4. **MIP formulation** can prove optimality for small N
5. **SparroWASM** is an external 2D nesting solver that some teams use

## The Fundamental Problem

All our optimization approaches converge to the SAME local optimum:
- SA, bbox3, gradient descent all find the same solution
- The baseline is at a strong local minimum
- Incremental improvements are tiny (0.001-0.02 per experiment)

## What We Haven't Tried

1. **MIP/Exact solvers** - Could prove optimality or find global optimum
2. **High-precision arithmetic** - Decimal instead of float
3. **External nesting solvers** (SparroWASM, JaguarPacker)
4. **Constructive heuristics** - Build solutions from scratch differently
5. **Per-N specialized strategies** - Different approach for each N range

In [3]:
# Let's check if there are any patterns in the baseline solution
# that could give us hints about what to try

# Check rotation angles used
print("Rotation angle distribution:")
all_angles = df['deg'].values
angle_counts = pd.Series(all_angles).value_counts().head(20)
print(angle_counts)

# Check if solutions are symmetric
print("\nChecking symmetry for N=10:")
n10 = df[df['n'] == 10]
print(n10[['x', 'y', 'deg']].values)

Rotation angle distribution:
113.629378    2
156.370622    2
259.564526    1
79.876469     1
259.562234    1
259.899941    1
79.731378     1
259.686381    1
79.736201     1
260.010896    1
259.578869    1
80.018805     1
79.888873     1
259.770008    1
79.731378     1
260.320241    1
259.277902    1
79.277902     1
80.089790     1
260.088932    1
Name: count, dtype: int64

Checking symmetry for N=10:
[[ 1.88012376e-01  3.95468339e-01  2.90150418e+02]
 [ 6.45156199e-01 -1.00307325e+00  3.38605911e+02]
 [-6.14391791e-01 -8.87597626e-02  2.14006324e+01]
 [ 2.32514891e-01 -5.31410422e-01  2.92608228e+02]
 [-2.02479980e-01 -5.35498066e-01  7.04216331e+01]
 [-6.49001733e-01 -9.87490676e-01  2.36293893e+01]
 [-2.36869866e-01  4.03073253e-01  6.63458358e+01]
 [ 6.49001869e-01 -3.07502968e-02  3.36262543e+02]
 [ 1.53594099e-01 -8.71498872e-01  1.15558948e+02]
 [-1.65713821e-01  6.70374082e-02  2.46345910e+02]]


In [4]:
# Calculate what improvement is needed per N to reach target
target = 68.919154
current = sum(scores.values())
gap = current - target

# If we could improve each N by the same percentage
pct_needed = gap / current * 100
print(f"Need {pct_needed:.2f}% improvement overall")

# What if we could only improve N=1-50?
n1_50_total = sum(scores[n] for n in range(1, 51))
print(f"\nN=1-50 total: {n1_50_total:.4f}")
print(f"If we improve N=1-50 by {gap/n1_50_total*100:.1f}%, we close the gap")

# What if we could only improve N=1-20?
n1_20_total = sum(scores[n] for n in range(1, 21))
print(f"\nN=1-20 total: {n1_20_total:.4f}")
print(f"If we improve N=1-20 by {gap/n1_20_total*100:.1f}%, we close the gap")

Need 2.41% improvement overall

N=1-50 total: 19.0333
If we improve N=1-50 by 9.0%, we close the gap

N=1-20 total: 8.0532
If we improve N=1-20 by 21.2%, we close the gap
